# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/maxiprogram/UnrealEngine
GAMEPROJECTFILE =/home/maxiprogram/Документы/Unreal Projects/Empty/Empty.uproject

TARGETS = \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	Empty-Linux-DebugGame  \
	Empty-Linux-Shipping  \
	Empty \
	EmptyEditor-Linux-DebugGame  \
	EmptyEditor-Linux-Shipping  \
	EmptyEditor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend EmptyEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug EmptyEditor-Linux-Debug


UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

Empty-Linux-DebugGame:
	 $(PROJECTBUILD) Empty Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

Empty-Linux-Shipping:
	 $(PROJECTBUILD) Empty Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

Empty:
	 $(PROJECTBUILD) Empty Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

EmptyEditor-Linux-DebugGame:
	 $(PROJECTBUILD) EmptyEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

EmptyEditor-Linux-Shipping:
	 $(PROJECTBUILD) EmptyEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

EmptyEditor:
	 $(PROJECTBUILD) EmptyEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
